name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_assets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    container:
      image: node:20
    env:
      THEME_NAME: base-theme-slug
    steps:
      - uses: actions/checkout@v2
      - name: Remove dist directory
        run: rm -rf themes/base-theme-slug/dist
      - name: Remove lock
        run: rm -rf themes/base-theme-slug/package-lock.json
      - name: Remove node_modules
        run: rm -rf themes/base-theme-slug/node_modules
      - name: Install npm packages
        run: npm --prefix themes/base-theme-slug/ install
      - name: Run production build
        run: npm --prefix themes/base-theme-slug/ run production
      - name: Remove node_modules directory
        run: rm -rf themes/base-theme-slug/node_modules
      - uses: actions/checkout@v2
      - name: Create deploy zips directory
        run: mkdir -p /deploy-zips/
      - name: copy theme
        run: |
          cd themes/
          cp -ra base-theme-slug /deploy-zips/base-theme-slug
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: base-theme-slug
          path: /deploy-zips/base-theme-slug  #
  
  create_release:
    runs-on: ubuntu-latest
    needs: [build_assets]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Release Tag
        id: get_tag
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: base-theme-slug
          path: ./base-theme-slug/
      - name: Zip artifact
        run: |
          cd ./base-theme-slug
          zip -r base-theme-slug.zip .
      - name: Create GitHub Release
        id: create_release_develop
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_develop.outputs.upload_url }}
          asset_path: ./base-theme-slug/base-theme-slug.zip
          asset_name: base-theme-slug.zip
          asset_content_type: application/zip
