name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_assets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    container:
      image: node:20
      
    env:
      THEME_NAME: base-theme-slug
    steps:
      - uses: actions/checkout@v2
      - name: Remove dist directory
        run: rm -rf themes/${{ env.THEME_NAME }}/dist
      - name: Install npm packages
        run: npm --prefix themes/${{ env.THEME_NAME }}/ install
      - name: Run production build
        run: npm --prefix themes/${{ env.THEME_NAME }}/ run production-github
      - name: Remove node_modules directory
        run: rm -rf themes/${{ env.THEME_NAME }}/node_modules

  create_pack_develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container:
      image: hacklab/alpine-3.14.2-zip:1.1.0
    env:
      THEME_NAME: base-theme-slug
    needs: build_assets

    steps:
      - uses: actions/checkout@v2
      - name: Create deploy zips directory
        run: mkdir -p /deploy-zips/
      - name: Zip theme
        run: |
          cd themes/
          zip -r /deploy-zips/${{ env.THEME_NAME }}.zip ${{ env.THEME_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.THEME_NAME }}-develop
          path: /deploy-zips/${{ env.THEME_NAME }}.zip

  create_pack_production:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    container:
      image: hacklab/alpine-3.14.2-zip:1.1.0
    env:
      THEME_NAME: base-theme-slug
    needs: build_assets

    steps:
      - uses: actions/checkout@v2
      - name: Create deploy zips directory
        run: mkdir -p /deploy-zips/
      - name: Zip theme
        run: |
          cd themes/
          zip -r /deploy-zips/${{ env.THEME_NAME }}.zip ${{ env.THEME_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.THEME_NAME }}-production
          path: /deploy-zips/${{ env.THEME_NAME }}.zip