name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_assets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    container:
      image: node:20
    env:
      THEME_NAME: teste-base
    steps:
      - uses: actions/checkout@v2
      - name: Remove dist directory
        run: rm -rf themes/teste-base/dist/*
      - name: Remove lock
        run: rm -rf themes/teste-base/package-lock.json
      - name: Remove node_modules
        run: rm -rf themes/teste-base/node_modules
      - name: Install npm packages
        run: npm --prefix themes/teste-base/ install
      - name: Run production build
        run: npm --prefix themes/teste-base/ run production
      - name: check files
        run:   ls -lhtra themes/teste-base
      - name: Remove node_modules directory
        run: rm -rf themes/teste-base/node_modules
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: teste-base
          path: themes/teste-base

  create_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build_assets]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Release Tag
        id: get_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: teste-base
          path: ./teste-base/
      - name: Zip artifact
        run: |
          cd ./teste-base
          ls
          zip -r teste-base.zip .
      - name: Create GitHub Release
        id: create_release_develop
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_develop.outputs.upload_url }}
          asset_path: ./teste-base/teste-base.zip
          asset_name: teste-base-${{ env.tag }}.zip
          asset_content_type: application/zip
